# Generated by Django 4.2.16 on 2024-11-14 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_customuser_character'),
        ('todo', '0008_todo_user'),
    ]

    operations = [
    ]
